config/routes.rb
Taskfish::Application.routes.draw do

  resources :events do
    member do
      get 'stream'
      get 'gallery'
      get 'location'
      get 'stats'
    end
  end

  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  namespace :api do
    namespace :v1 do

      post 'users/create' => 'user#create'
      get 'users/:id' => 'user#show'

      get 'users/:user_id/events' => 'event#index'
      get 'users/:user_id/events/:event_id' => 'event#show'
      delete 'users/:user_id/events/:event_id' => 'event#remove'
      post 'users/:user_id/events/create' => 'event#create'
      post 'users/:user_id/events/:event_id/invite' => 'event#invite'
      get '/users/:user_id/events/:event_id/posts/:post_id' => 'event#post'
      get 'users/:user_id/events/:event_id/stats' => 'event#stats'
      get 'users/:user_id/events/:event_id/im_in' => 'event#im_in'
      get 'users/:user_id/events/:event_id/im_out' => 'event#im_out'
      post 'users/:user_id/events/:event_id/comment' => 'comment#create_event_comment'
      get 'users/:user_id/events/:event_id/comments' => 'comment#get_event_comments'
      post 'users/:user_id/events/:event_id/pictures/:picture_id/comment' => 'comment#create_picture_comment'
      get 'users/:user_id/events/:event_id/pictures/:picture_id/comments' => 'comment#get_picture_comment'

      post 'users/:user_id/events/:event_id/pictures/create' => 'picture#create'
      get 'users/:user_id/events/:event_id/pictures' => 'picture#index'
      get 'users/:user_id/events/:event_id/pictures/:picture_id' => 'picture#show'
      delete 'users/:user_id/events/:event_id/pictures/:picture_id' => 'picture#remove'
      get 'users/:user_id/events/:event_id/posts/:post_id/like' => 'picture#like'
      get 'users/:user_id/events/:event_id/posts/:post_id/comment' => 'picture#comment'

      get 'users/:user_id/events/:event_id/like' => 'like#like_event'
      get 'users/:user_id/events/:event_id/likes' => 'like#event_likes'

    end
  end

  

end

app/views/notifier/event_expiry.html.erb
Hello <%= @user.name %>,

  We just wanted to let you know that the event “<%= @event.title %>” you created through TaskFish has auto expired. We wiped , deleted, and purged all the photos ,     comments, and history of the event. Just for the records your event had <%= @event.pictures.length %> photos, <%= @event.pictures.length %> comments, and <%= @event.im_in.length %> number of people.

  —TaskFish Team

app/views/notifier/invitation.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
<h1>Hello There!</h1>
<p>
  You have received a invitation to a part via TaskFish.com. Your friend <%= @user.name %>
  Would love for you to join the fun, either install the app through the app store <link to app store> ,
  or you can view the party online at this website <%= event_url(@event) %>
  “
  Remember with TaskFish you can share and comment on the party or event, and after 24 hours everything gets removed.
  So go have a safe fun time, enjoy the party responsibility.. And let us take care of deleting all the evidence
</p>

</body>
</html>