config/routes.rb
Taskfish::Application.routes.draw do

  resources :events do
    member do
      get 'stream'
      get 'gallery'
      get 'location'
      get 'stats'
    end
  end

  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  namespace :api do
    namespace :v1 do

      post 'users/create' => 'user#create'
      get 'users/:id' => 'user#show'

      get 'users/:user_id/events' => 'event#index'
      get 'users/:user_id/events/:event_id' => 'event#show'
      delete 'users/:user_id/events/:event_id' => 'event#remove'
      post 'users/:user_id/events/create' => 'event#create'
      post 'users/:user_id/events/:event_id/invite' => 'event#invite'
      get '/users/:user_id/events/:event_id/posts/:post_id' => 'event#post'
      get 'users/:user_id/events/:event_id/stats' => 'event#stats'
      get 'users/:user_id/events/:event_id/im_in' => 'event#im_in'
      get 'users/:user_id/events/:event_id/im_out' => 'event#im_out'
      post 'users/:user_id/events/:event_id/comment' => 'comment#create_event_comment'
      get 'users/:user_id/events/:event_id/comments' => 'comment#get_event_comments'
      post 'users/:user_id/events/:event_id/pictures/:picture_id/comment' => 'comment#create_picture_comment'
      get 'users/:user_id/events/:event_id/pictures/:picture_id/comments' => 'comment#get_picture_comment'

      post 'users/:user_id/events/:event_id/pictures/create' => 'picture#create'
      get 'users/:user_id/events/:event_id/pictures' => 'picture#index'
      get 'users/:user_id/events/:event_id/pictures/:picture_id' => 'picture#show'
      delete 'users/:user_id/events/:event_id/pictures/:picture_id' => 'picture#remove'
      get 'users/:user_id/events/:event_id/posts/:post_id/like' => 'picture#like'
      get 'users/:user_id/events/:event_id/posts/:post_id/comment' => 'picture#comment'

      get 'users/:user_id/events/:event_id/like' => 'like#like_event'
      get 'users/:user_id/events/:event_id/likes' => 'like#event_likes'

    end
  end

  

end

app/models/event.rb
class Event

  include MongoMapper::Document
  include Paperclip::Glue

  key :title , String , :required => true
  key :venue , String
  key :event_location , String
  key :event_date , Time
  key :latitude , Float
  key :longitude , Float
  key :last_comment_id , Integer
  key :last_picture_id , Integer
  key :created_by_name , String

  key :is_active , Boolean , :default => true



  key :expire_at , Time

  key :user_ids , Array

  key :im_in , Array
  key :attendant_profile_images , Array
  key :im_in_names , Array

  key :created_by_profile_picture

  key :cover_photo , String

  timestamps!

  auto_increment!

  many :users , :in => :user_ids

  many :comments
  many :pictures

  has_attached_file :cover_pic

  key :cover_pic_file_name, String

  #scope :active , where(:expire_at.gte => Time.now )
  scope :active , where(:is_active => true )


  belongs_to :user

  many :likes

  def expire_after
    x = (expire_at - Time.now)/3600
    hours = x.to_i/60
    minutes = x.to_i % 60
    "#{hours} hours and #{minutes} left"
  end

  def organizer
    self.user
  end

  def participants
    participants = self.users
    participants << self.user
    participants
  end

  def male_participants
    self.participants.all(:sex => "m")
  end

  def female_participants
    self.participants.all(:sex => "f")
  end

end

app/controllers/api/v1/event_controller.rb
module Api
  module V1
    class EventController < ApplicationController

      def index

        user = User.find_by_id2 params[:user_id].to_i

        response = { :message => 'Failed to fetch events for specified user' , :status => 104 }
        #binding.pry
        if user.present?
          #response = Event.where(:user_id => user.id, :expire_at.gt => Time.now)
          response = user.get_all_events
        end

        respond_to do |format|
          format.json { render :json => response }
        end

      end

      def show

        user = User.find_by_id2 params[:user_id].to_i
        event = Event.find_by_id2 params[:event_id].to_i

        response = { :message => 'Failed to fetch event by specified event id' , :status => 109 }

        response = event if event.present?

        respond_to do |format|
          format.json { render :json => response }
        end

      end

      def stats

        user = User.find_by_id2 params[:user_id].to_i
        event = Event.find_by_id2 params[:event_id].to_i

        response = { :message => 'Failed to fetch event by specified event id' , :status => 109 }

        if event.present?
          statistics = { event: event}
          statistics[:total_participants] = event.im_in.length
          male_participants = 0
          event.im_in.each do |u|
            u = User.find_by_id2 u.to_i
            male_participants = male_participants + 1 if u.sex == "male"
          end
          statistics[:male_participants] = male_participants
          statistics[:female_participants] = event.users.length - male_participants
          response = statistics
        end

        respond_to do |format|
          format.json { render :json => response }
        end

      end

      def post
        user = User.find_by_id2 params[:user_id].to_i
        event = Event.find_by_id2 params[:event_id].to_i
        post_id = params[:post_id]

        event_post = event.pictures.select{|e| e if e.id.to_s == post_id }
        p_like = event_post.first.likes.select{|l| l if l.user_id == user.id.to_s }

        response = { post: event_post.first , liked: p_like.present? }
        respond_to do |format|
          format.json { render :json => response }
        end


      end

      def remove

        user = User.find_by_id2 params[:user_id].to_i
        event = Event.find_by_id2 params[:event_id].to_i

        response = { :message => 'Failed to fetch event by specified event id' , :status => 110 }

        if event.present?
          event.delete
          response = { :message => 'Event deleted successfully' , :status => 0 }
        end

        respond_to do |format|
          format.json { render :json => response }
        end

      end

      def im_in
        user = User.find_by_id2 params[:user_id].to_i
        event = Event.find_by_id2 params[:event_id].to_i
        unless event.im_in.include?(user.id2)
          event.im_in << user.id2
          event.attendant_profile_images << user.profile_image_url
          event.im_in_names << user.name
          user.attended_count = user.attended_count + 1
          user.save
        end
        event.save
        response = { :message => 'User step into event successfully' , :status => 200 }
        respond_to do |format|
          format.json { render :json => response }
        end
      end

      def im_out                                            s
        user = User.find_by_id2 params[:user_id].to_i
        event = Event.find_by_id2 params[:event_id].to_i
        event.im_in.delete(user.id2)
        event.attendant_profile_images.delete(user.profile_image_url)
        event.im_in_names.delete(user.name)
        event.save
        user.attended_count = user.attended_count - 1
        user.save
        response = { :message => 'User out of event successfully' , :status => 200 }
        respond_to do |format|
          format.json { render :json => response }
        end
      end

      def create

        user = User.find_by_id2 params[:user_id].to_i

       if user.present?

          event = Event.new(params)
          #@event.title = params[:title]
          #@event.venue = params[:venue]
          #@event.event_date = Time.parse(params[:event_date])
          #@event.latitude = params[:latitude]
          #@event.longitude = params[:longitude]
          #@event.save
          #binding.pry
          event.created_by_name = user.name
          event.created_by_profile_picture = user.profile_image_url
          event.user = user
          event.users << user
          event.expire_at = Time.parse(params[:event_date]) + params[:expire_after].to_i.hours
          #@event.cover_photo = @event.cover_pic
          event.im_in << user.id2
          event.attendant_profile_images << user.profile_image_url
          event.im_in_names << user.name
          event.save

          event.cover_photo = event.cover_pic
          event.save
          respond_to do |format|
              user.events << event
              user.created_count = user.created_count + 1
              user.attended_count = user.attended_count + 1
              user.save
              format.json { render :json => event }
          end
        else
          respond_to do |format|
            format.json { render :json => { :message => 'Failed to create event' , :status => 105 } }
          end
        end

      end

      def invite

        user = User.find_by_id2 params[:user_id].to_i
        event = Event.find_by_id2 params[:event_id].to_i

        response = { :message => 'Failed to invite users' , :status => 104 }

        if event.present?

          user_invited = User.find_by_email params[:email]
          if user_invited.present?
            user_invited.events << event
            event.users << user_invited
            user_invited.invites_count = user_invited.invites_count + 1
            #event.attendant_profile_images << user_invited.profile_image_url
            user_invited.save
          end
          Notifier.invitation(user,params[:email],event).deliver
          event.save
          response = { :message => 'User invited successfully' , :status => 0 } if event.save
        end

        respond_to do |format|
          format.json { render :json => response }
        end

      end

      def invite_backup

        user = User.find_by_id2 params[:user_id].to_i
        event = Event.find_by_id2 params[:event_id].to_i

        response = { :message => 'Failed to invite users' , :status => 104 }
        if event.present?
          params[:user_ids].each do |user_id|
            user_invited = User.find_by_id2 user_id.to_i
            if user_invited.present?
              user_invited.events << event
              event.users << user_invited
              user_invited.save
            end
          end
          event.save
          response = { :message => 'User invited successfully' , :status => 0 } if event.save
        end

        respond_to do |format|
          format.json { render :json => response }
        end

      end


    end

  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController


  def index
    @user = User.find_by_id params[:user_id]
    @events = []
    if @user.present?
      @events = @user.get_all_events
    end
  end

  def show
    @event = Event.last #find_by_id params[:id]
    redirect_to stream_event_path(@event)
  end

  def stream
    @event = Event.find_by_id params[:id]
  end

  def gallery
    @event = Event.find_by_id params[:id]
  end

  def location
    @event = Event.find_by_id params[:id]
  end

  def stats
    @event = Event.find_by_id params[:id]
  end

end

app/helpers/event_helper.rb
module EventHelper
end

app/views/events/_event_detail_header.html.erb
<div class="detail-header">
    <div class="half pull-left">
       <div class="event-title"><%= @event.title %></div>
       <br/><br/><br/>
      <div class="event-timing"><%= @event.event_date %></div>
      <div class="event-venue"><%= @event.venue %></div>

    </div>
    <div class="half pull-right">
      <div class="pull-left">
        <%= image_tag(@event.created_by_profile_picture , :class => "round_img_lrg margin-20") %>

      </div>
      <div class="created_by">
        By <br/><%= @event.created_by_name %>
      </div>

      <div class="clearfix"></div>

      <div class="round_img_lrg margin-20 pull-left">
        <%= @event.im_in.length %>
      </div>

      <div class="fish_in_the_party">
        fish in the party: <br>
        <% @event.attendant_profile_images.first(5).each do |attendant_img| %>
          <%= image_tag(attendant_img,:class => "round_img") %>
        <% end %>
      </div>
      <div class="clearfix"></div>
      <div class="content_will_delete">
        CONTENT WILL BE DELETED IN 4 HOURS AND 38 MINUTES
      </div>
    </div>
</div>

app/views/events/_event_navigation_bar.html.erb
<div class="event-navigation">
  <span class="navigation-link <%= "active" if active_tab == "stream" %>"><%= link_to 'Stream' , stream_event_path(@event) %></span>
  <span class="navigation-link <%= "active" if active_tab == "gallery" %>"><%= link_to 'Gallery' , gallery_event_path(@event) %></span>
  <span class="navigation-link <%= "active" if active_tab == "location" %>"><%= link_to 'Locations' , location_event_path(@event) %></span>
  <span class="navigation-link <%= "active" if active_tab == "stats" %>"><%= link_to 'Stats' , stats_event_path(@event) %></span>
</div>

app/views/events/gallery.html.erb
<%= render 'event_detail_header' %>
<%= render 'event_navigation_bar', :active_tab => "gallery" %>


<div class="event-content-area">
  <br/>
  &nbsp;<%= @event.pictures.length %> pictures
  <br/><br/>
  <div class="gallery">
    <%= image_tag(@event.created_by_profile_picture, :class => 'gallery_img') %>
    <%= image_tag(@event.created_by_profile_picture, :class => 'gallery_img') %>
    <%= image_tag(@event.created_by_profile_picture, :class => 'gallery_img') %>
    <%= image_tag(@event.created_by_profile_picture, :class => 'gallery_img') %>
    <%= image_tag(@event.created_by_profile_picture, :class => 'gallery_img') %>
    <%= image_tag(@event.created_by_profile_picture, :class => 'gallery_img') %>
    <%= image_tag(@event.created_by_profile_picture, :class => 'gallery_img') %>

  </div>

</div>

app/views/events/index.html.erb
Events: <%= @events.length %>

app/views/events/location.html.erb
<%= render 'event_detail_header' %>
<%= render 'event_navigation_bar', :active_tab => "location" %>


<div class="event-content-area">
  <br/>
  &nbsp;1 Location
  <br/><br/>
  <div style='width: 60%; margin-left: 5%;' class="pull-left">
    <div id="map" style='width: 100%; height: 300px;'></div>
  </div>
  <div class="location_address">
    <%= @event.event_location %>
  </div>
</div>
<br/><br/><br/><br/><br/>

<script>
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers([
            {
                "lat": 0,
                "lng": 0,

                "infowindow": "<%= @event.event_location %>"
            }
        ]);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
    });
</script>

app/views/events/show.html.erb
<%= render 'event_detail_header' %>
<%= render 'event_navigation_bar' %>


<div class="event-content-area">
  <h1><%= @event.title rescue "abcd" %></h1>
</div>

app/views/events/stats.html.erb
<%= render 'event_detail_header' %>
<%= render 'event_navigation_bar', :active_tab => "stats" %>


<div class="event-content-area">
  stats are here
  <h1><%= @event.title rescue "abcd" %></h1>
</div>

app/views/events/stream.html.erb
<%= render 'event_detail_header' %>
<%= render 'event_navigation_bar',:active_tab => "stream" %>


<div class="event-content-area">
  Streaming
  <h1><%= @event.title rescue "abcd" %></h1>
</div>